name: igtools
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.14.0
  envied: ^0.5.4+1
  crypto: ^3.0.0
  mysql_client: ^0.0.27
  postgres: ^3.4.0
  http: ^1.2.2
  minio: ^3.5.2
  mailer: ^6.2.0
  uuid: ^4.5.0
  image_compression: ^1.0.5
  

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
  hive: ^2.2.3
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.12
